### ISSUE TITLE
Zoom value not always correct

### ISSUE THREAD

**Issue by jvkaam** [cyotek/Cyotek.Windows.Forms.ImageBox#20]
When I show the Zoom value in the immediate window and I'm zooming in and out by using the mousewheel the value goes down when scrolling the mouse wheel down but when you scroll up again the first value first goes down and then it goes up. So suppose I'm zooming in and the zoom goes from 25, 30 50 and then at 70 I think oh thats to big so I go back wanting to go 50 but instead the value shows 100. It looks as if the directions the first time goes wrong.
I have tried the Mousewheel event and the ZoomChanged event and worked with latest v2.0.50727 version (but reproduced it also in older versions).
Thanks for looking into this.

Update: When I tried to break down the problem (which I should have before posting here ;-) it somehow solved the problem. Don't know what caused it. So never mind.

**Comment by cyotek** [comment]
Hello,

Thanks for posting the issue. I did take a (fairly brief) look at this, but as you mentioned in your update, it seems to be working fine for me too. 

Feel free to raise a new issue if you do find a specific problem where it doesn't work as expected. There is also issue #8 which may or may not be related and I still haven't found dedicated time to look at.

Regards;
Richard Moss
