### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Prakash19921206** [cyotek/Cyotek.Windows.Forms.ImageBox#24]
hi
i noticed a small bug when dynamically allocating `imageBox `to `tableLayoutPanel `and removing/clearing `imageBox `back
i tried in C++/Cli (Winforms)

in form load event i created tableLayoutPanel with 25 cells (5 rows, 5 column) in each cell i placed a new instance of imageBox. (i noticed a hike of 20 - 30mb in memory consumption in visual studio's diagnostic tool) 

now, how to free memory occupied by imageBox, if i call [TableLayoutPanel.Controls.Clear ](http://stackoverflow.com/questions/15586347/how-deep-does-controls-clear-clean-up), this doesn't free up memory. so i have to call `Dispose `right?

can you expose `Dispose `func, because as of now it says `Dispose `cannot be called by pointer or object?

Note: closing form or calling `System.GC.Collect `frees up memory
Thank you

**Comment by cyotek** [comment]
Sorry for not noticing this earlier. Anything implementing from `Control` already has a public `Dispose` method, and `ImageBox` is no exception - I'm not familiar with C++; about all I can say is `Dispose` is definitely present.

**Comment by Prakash19921206** [comment]
i just remembered that in C++/Cli  even though i can call `Dispose ` method without any error. i have to use `delete `keyword. 
for ex:
```
ImageBox ^imageBox1 = gcnew ImageBox(); //creating a object
delete imageBox1; //proper method to Dispose
```
Hope this helps someone using C++/Cli
Thanks for your reply
