### ISSUE TITLE
Multiple Text

### ISSUE THREAD

**Issue by Prakash19921206** [cyotek/Cyotek.Windows.Forms.ImageBox#28]
Hi.
i wanted to display a text with transparent background on video (using `imageBox`)
if i use a `label `and set its `background to transparent `and make `parent = ImageBox ` then it flickers a bit (performance issues)
I know `ImageBox `has 'Text' field that's amazing, it works well.
but can we add multiple text at different locations?

Thanks & Regards
Prakash

**Comment by cyotek** [comment]
The default implementation of the `ImageBox` control can't support displaying multiple text strings at different places. However, the control does expose a `DrawLabel` method (it's `protected` so could only be called from a control inheriting from `ImageBox`) which will draw text for you, coloured and aligned appropriately, including the ability to scale the text to match the zoom level. By overriding `OnPaint` in the inherited control, you can perform the base drawing, then call `DrawLabel` to perform any custom text painting. For example, you could add a new `Texts` property and related collection to make it reusable in your own code.

Alternatively, just hook into the `Paint` event for your existing `ImageBox` instance and use `TextRenderer.DrawText` (or `Graphics.DrawString`) to add your own painting of strings.

Either of these methods should avoid the flickering you described as they would be part of the native paint cycle of the control.

**Comment by Prakash19921206** [comment]
Ok
Thank you
