### ISSUE TITLE
Image Alignment

### ISSUE THREAD

**Issue by fdncred** [cyotek/Cyotek.Windows.Forms.ImageBox#29]
Is there a way to align the image to the Left, Center, or Right side of the imageBox control? It seems to center by default.

Thanks,
Darren

**Comment by cyotek** [comment]
Hello,

Thanks for the question. If the image will entirely fit in the `ImageBox` on at least one axis, then it will be centred, unless the `AutoCenter` property is `false`, in which case it will appear in the top left corner. There isn't a way to right align it at present, I would have expected it would be quite confusing for it to align right and then scroll right (although now that this is mentioned I suppose the default behaviour of on the left would be just as confusing in an RTL environment).

So left or centre are current your only options - hope that's sufficient!

Regards;
Richard Moss

**Comment by fdncred** [comment]
Yup. That's good enough. I wanted it left justified anyway. Thanks for the tip!
