### ISSUE TITLE
Integration with Accord.NET.Framework

### ISSUE THREAD

**Issue by fdncred** [cyotek/Cyotek.Windows.Forms.ImageBox#30]
FYI - Thanks for the great tool. I wanted to let you know that I've just committed it into our [codebase](https://github.com/accord-net/framework/tree/development/Sources/Accord.Controls.Cyotek.ImageBox).

Learn more about our [framework](http://accord-framework.net/).

We appreciate the MIT license.

Regards,
Darren

**Comment by cyotek** [comment]
Hello,

Thanks for the notification, glad you found the control useful!

Regards;
Richard Moss
