### ISSUE TITLE
How to get image Point use mouse position?

### ISSUE THREAD

**Issue by unominhtuan** [cyotek/Cyotek.Windows.Forms.ImageBox#36]
I want to move the mouse on the image and return the coordinates of the image at the mouse position, is there any way to do this?

**Comment by cyotek** [comment]
Did you check the demonstration application which comes with the control? This shows an example of this functionality.

You can use the `IsPointInImage` and `PointToImage` methods, for example

```
private void imageBox_MouseMove(object sender, MouseEventArgs e)
{
  if (imageBox.IsPointInImage(e.Location))
  {
    Point imagePixel;

    imagePixel = imageBox.PointToImage(e.Location);
  }
}
```
