### ISSUE TITLE
easy request - expose minzoon/maxzoom as properties

### ISSUE THREAD

**Issue by mtagliaf** [cyotek/Cyotek.Windows.Forms.ImageBox#4]
Wondering if you would consider exposing minzoom/maxzoom as properties (but still not exceeding 1/3500).  I have an application where I want to allow zooming in but not zooming out.

thanks

**Comment by mtagliaf** [comment]
also... can you get the version in NuGet to be current.  Thx!  (LOVE the control)

**Comment by cyotek** [comment]
I assume you mean as read/write properties? They were never exposed before as I wasn't certain of the default values, and as the defaults seemed to have worked over the years I forgot about it. Assuming they even have a purpose now, I can't remember off the top of my head.

Have you tried changing the `ZoomLevels` property - this collection stores all the incremental zoom steps, so if you wanted to limit the range this should do the job.

In regards to the NuGet package, yes I do need to update it. I'll do that next update once I decide what I'm doing with merging in parts of `ImageBoxEx`.

Glad you like the control :)

Regards;
Richard Moss

**Comment by mtagliaf** [comment]
`ZoomLevels` did the trick.  Very cool.  Thanks.

**Comment by cyotek** [comment]
Great, thanks for letting me know!
