### ISSUE TITLE
Image graphics disappear when zooming out

### ISSUE THREAD

**Issue by TomerEphraim** [cyotek/Cyotek.Windows.Forms.ImageBox#41]
Hi there, 

I have a `System.Drawing.Bitmap` image with some painted graphics on it.

I then add this bitmap image to the `ImageBox`.

```
System.Drawing.Bitmap imgWithGraphics;
...
draw some graphics on image
...
Cyotek.Windows.Forms.ImageBox Imgbox;
...
Imgbox.Image = imgWithGraphics;
```

When I zoom out via the ImageBox to the level where the bitmap is smaller than the boundary of the image box, the graphics on the image disappear. when I zoom in to the original level - the graphics appear back. 

Is there a way to zoom out properly without loosing the graphics?

**Comment by TomerEphraim** [comment]
It seems that this problem is due to interpolation. 
The pen width that I draw the graphics with is set to 1. If I increase it than the graphics won't disappear (at least until some it's zoomed out far enough).

**Comment by cyotek** [comment]
I know you seemed to have solved the problem on your own, but the control offers a few methods that help with custom drawing . `GetOffsetPoint` and `GetOffsetRectangle` can be used to take a source value and reposition/resize it according to the current scroll and zoom settings. `GetScaledPoint` and `GetScaledRectangle` will resposition/resize based on zoom, but not scroll.

For pen size, you could multiple your starting size by the `ZoomFactor` property.
