### ISSUE TITLE
Is this project still maintained? What about the nuget package?

### ISSUE THREAD

**Issue by PmE8HW0KRfqa** [cyotek/Cyotek.Windows.Forms.ImageBox#42]
Thanks for putting the work into this project.

Is this project still being maintained? What about the nuget package? It hasn't been updated since 2017.

**Comment by cyotek** [comment]
Yes, just not as often as I would wish! I had been working on an off on a large revamp to get rid of some of the inherited bases to allow user requests like hide scrollbars but other work usually takes priority.

Is there any particular issue with the current package that is causing a problem or an outstanding issue to address? The control isn't broken or anything so the package... 3 years old as it may be... is perfectly fine.

**Comment by PmE8HW0KRfqa** [comment]
No issues in particular. Just curious if it was still active. Thanks for providing the control. It works really well.
