### ISSUE TITLE
Wrong scrolling in CanPan method

### ISSUE THREAD

**Issue by wmjordan** [cyotek/Cyotek.Windows.Forms.ImageBox#45]
There are two `HScroll`s in the line 4839 of ImageBox.cs and one of them should be `VScroll`.

https://github.com/cyotek/Cyotek.Windows.Forms.ImageBox/blob/f1d2f4871d03fc0f96ee960ea757468b64a71a00/Cyotek.Windows.Forms.ImageBox/ImageBox.cs#L4839

**Comment by cyotek** [comment]
Well... drat.

Thanks for finding that bit of stupidity!

**Comment by wmjordan** [comment]
A user complained panning was not working after resizing the application window with the ImageBox.
After digging around the source code of mine, for about an hour, then this repository, I found that.

Would you please take the trouble to release a new NuGet package when you fix this?

**Comment by cyotek** [comment]
Hello,

I reproduced it using the demo and I've pushed a fixed, including a new package - 1.3.1. 

It isn't present in the multi target branch (yet!) though so there's no updated 2.0 package.

**Comment by wmjordan** [comment]
Thank you very much for the quick response!
