### ISSUE TITLE
Сan't distinguish click and panning event

### ISSUE THREAD

**Issue by dmitry-abt** [cyotek/Cyotek.Windows.Forms.ImageBox#50]
Hi there!

Starting from version 1.3.0, events for a panning image began to work strangely.
With a normal click (cursor coordinates do not change), events occur in the following order:
1. PanStart 
3. Click
4. PanEnd

When I work with panning image the value of the property IsPanning is always true, because during the click PanStart event is always raised before OnClick event (even during a simple click when cursor coordinates do not change).

In versions prior to 1.3.0, there were no events before the click.

![131](https://user-images.githubusercontent.com/52600333/206733503-0824c5ba-bfb9-4e2a-96a0-e64b0c4af3dd.gif)
![121](https://user-images.githubusercontent.com/52600333/206733489-01110bcf-a8b2-4275-8fcc-8c6ed955a7f4.gif)

**Comment by snechaev** [comment]
I hit the same problem. 
In my case the `IsPanning` is always `true` inside a `click` handler so it is impossible to distinguish between "click" and "drag to pan" actions.

A quick research shown that a problem was introduced into rev. 3aa026b72eb9d80682e97ea87b8514b6f7450d3a (Added PanMode and AllowFreePan properties). In this revision the `ProcessPanning` is called directly from `OnMouseDown` handler (so, before the `click` event) and when `click` event happens, the pan is already started and `IsPanning=true`.

https://github.com/cyotek/Cyotek.Windows.Forms.ImageBox/blob/2fb350f4173e6dd68d5540b30ab0d2f9d4aba7eb/Cyotek.Windows.Forms.ImageBox/ImageBox.cs#L4018-L4030

It looks like this can be fixed just by adding additional checks for `AllowFreePan` and mouse button and then call `ProcessPanning` only if Free Pan is enabled and the button is middle button. 

I will provide a pull request with the fix, but I'm unsure that such a fix will play good with all the features and modes of ImageBox.
