### ISSUE TITLE
Keep painted drawing on Imagebox after zoom or pan

### ISSUE THREAD

**Issue by Zeeshanef** [cyotek/Cyotek.Windows.Forms.ImageBox#56]
Is there any provision in this control to keep painted drawing on Imagebox after zoom or pan.

For example if I draw a following object so it does not move with the image position.

```
private void ImageBoxEx1_Paint(object sender, PaintEventArgs e)
    {
      if (drawRectangle)
      {
        using (Pen pen = new Pen(Color.Red, 2))
        {
          e.Graphics.DrawRectangle(pen, RectDraw);
        }
      }
    }
```

**Comment by ext2txe** [comment]
It's your paint event's responsibility to handle the correct scaling of any overlays that need to be painted over the image.

There's an example of how to do this in one of the closed issues.

**Comment by Zeeshanef** [comment]
Actually I was looking for `Rectangle OffSetRect = imageBox1.GetOffsetRectangle(RectDraw)`

**Comment by Zeeshanef** [comment]
Using GetOffsetRectangle method fixed the issue.
