### ISSUE TITLE
ImageBox selection gets unselected when expanding selection to the right end.

### ISSUE THREAD

**Issue by corientdev** [cyotek/Cyotek.Windows.Forms.ImageBox#6]
Hi,

Thanks for the wonderful library.

I think there is a bug in latest version. 

ImageBox selection gets unselected when expanding selection to the right end.

It was working fine till commit 97ebd6da3b7dfbbda35cb97e799dd12db7337966

**Comment by cyotek** [comment]
Hello,

Thanks for the report - just give a go and confirmed it. I'll try and find some time to correct that this weekend.

Thanks again!

Regards;
Richard Moss

**Comment by cyotek** [comment]
Fixed in latest commits, thanks again for the catch.
