### ISSUE TITLE
MouseWhell zoom or scroll

### ISSUE THREAD

**Issue by fabiencomte** [cyotek/Cyotek.Windows.Forms.ImageBox#9]
Hello,

I wish to do a zoom when pressing ctrl during mousewheel else a simple vertical scroll but i don't know how to modify the code. Can someone give me some steps please ?

I guess that i have to override onMouseWheel. Select depending if ctrl is pressed and use ProcessMouseZoom but protection is not accepted so i have a doubt. Is there any function to manage scroll too ?

**Comment by cyotek** [comment]
Hello, and thanks for the question. I took a quick look at this, and found it reasonable easy to do by overriding `OnMouseWheel`. There is a caveat though - the `MouseWheel` event will no longer be raised unless `Control` is held.

You can find my implementation below - I check to see if `Control` is pressed and if so, use the default implementation. If it isn't pressed, I then check to see if a vertical scrollbar is present, and if so get the current `AutoScrollPosition` property value, offset it by the wheel delta (making sure it doesn't fall out of the boundaries of the scrollbar), and then re-apply it. Seems to work fine - you could adapt the same code to scroll the horizontal scroll, or to scroll horizontally if a vertical scrollbar isn't present.

```c#
protected override void OnMouseWheel(MouseEventArgs e)
{
  if ((Control.ModifierKeys & Keys.Control) != 0)
  {
    base.OnMouseWheel(e);
  }
  else if (this.VScroll)
  {
    Point position;
    int value;

    position = this.AutoScrollPosition;

    value = Math.Min(Math.Max(-position.Y - e.Delta, 0), this.VerticalScroll.Maximum);

    this.AutoScrollPosition = new Point(-position.X, value);
  }
}
```

Hope this information helps!

Regards;
Richard Moss

**Comment by fabiencomte** [comment]
I will try that asap.
Thank you for your help.
